(do
  (require 'clojure.edn 'clojure.string 'futon3c.agency.roster-store
           'futon3c.agency.registry 'futon3c.transport.http
           'futon3c.apm.problem-queue-supervisor)
  (let [read-doc #(clojure.edn/read-string (slurp %))
        packet "holes/labs/M-apm-demonstration/analysis/v3-decommission-2026-09-12/"
        q (read-doc "data/apm-campaigns/jit-all-open-v3/queue-state.edn")
        c (read-doc "data/apm-campaigns/jit-all-open-v3/coordinator.edn")
        entry (get-in (read-doc "data/apm-coordinators/registry.edn") [:entries "jit-queue:jit-all-open-v3"])
        archived (read-doc (get-in q [:decommission/receipt :archive :path]))
        pre (read-doc (str packet "pre-decommission.edn"))
        frame-ids (set (:frame-ids pre))
        ours? #(contains? frame-ids (first (clojure.string/split % #"-")))
        registered (filter ours? (keys (:agents (futon3c.agency.registry/registry-status))))
        roster (read-doc (futon3c.agency.roster-store/roster-store-path))
        restorable (filter #(ours? (:agent-id %)) (:agents roster))
        jobs (into {} (filter (fn [[id _]] (ours? id))) (futon3c.transport.http/active-invoke-job-counts-full-scan))
        result {:at (str (java.time.Instant/now)) :queue/status (:status q)
                :queue/valid? (futon3c.apm.problem-queue-supervisor/valid-state? q)
                :active (:active q) :resumptions (:resumption-queue q)
                :unresolved-parks (mapv :frame/id (filter #(= :awaiting-decision (:decision/status %)) (:parked q)))
                :completed-history-preserved? (= (:completed archived) (:completed q))
                :park-history-preserved? (= (:parked archived) (:parked q))
                :store-warning-history-preserved? (= (:store-read/repairs archived) (:store-read/repairs q))
                :coordinator/enabled? (:coordinator/enabled? entry)
                :coordinator/status (:regulator/status c) :tick-claim (:regulator/tick-claim c)
                :remaining-registered (vec registered) :remaining-restorable (mapv :agent-id restorable)
                :active-job-counts jobs
                :deferred-work (select-keys (get-in archived [:active :frame]) [:frame/id :problem/id])}]
    (spit (str packet "verified.edn") (pr-str result))
    (assert (= :decommissioned (:queue/status result)))
    (assert (:queue/valid? result))
    (assert (nil? (:active result)))
    (assert (empty? (:unresolved-parks result)))
    (assert (:completed-history-preserved? result))
    (assert (:park-history-preserved? result))
    (assert (:store-warning-history-preserved? result))
    (assert (false? (:coordinator/enabled? result)))
    (assert (= :stopped (:coordinator/status result)))
    (assert (nil? (:tick-claim result)))
    (assert (empty? registered))
    (assert (empty? restorable))
    (assert (empty? jobs))
    result))
