(ns futon3c.diagramprover.wm-wire-flight-run-flight-driver-summary-readings-test
  (:require [clojure.test :refer [deftest is]] [futon3c.diagramprover.wm-wire :as w] [futon3c.diagramprover.wm-wire-producer-record :as producer-record]))
(def wire-id [:flight-run :flight-driver-summary :readings])
(def producer (delay (producer-record/record "wm-wire-flight-run-flight-driver-summary-readings-test-liter")))
(defn observe ([] (get-in @producer [:wires wire-id :primary])) ([_] (get-in @producer [:wires wire-id :different])))
(defn check [] (observe))
(def wire {:wire wire-id :kind :witnessed-hermetically :test `the-flights-readings-reach-the-drivers-summary :check check :live-records-read []})
(deftest the-flights-readings-reach-the-drivers-summary (let [o (check)] (is (= :closed (:status o))) (is (= 1 (count (:writer o)))) (is (= #{:criteria :constraints} (set (map :kind (:asked (first (:writer o))))) (set (map :kind (:projection o))))) (is (= 1 (:before-click (first (:writer o))))) (is (w/received? o))))
(deftest a-typed-absence-at-the-reader-fails-the-wire (let [o (check)] (is (not (w/received? (assoc o :reader {:absent :no-readings})))) (is (not (w/received? (assoc o :reader {:status :absent :reason :no-readings}))))))
(deftest a-different-flights-readings-fail-the-wire (let [o (check) other (observe :different)] (is (some? (:reader other))) (is (not= (:writer o) (:reader other))) (is (not (w/received? (assoc o :reader (:reader other)))))))
(deftest the-live-records-carry-the-writers-end-only (is (map? @producer)))
