(ns futon3c.diagramprover.wm-wire-producer-wm-wire-flight-record-summary-flight-click-close-test-chosen-test
  (:require [clojure.edn :as edn] [clojure.java.io :as io] [clojure.test :refer [deftest is testing]]
            [futon2.aif.flight :as flight] [futon2.aif.flight-runner :as fr] [futon2.aif.full-loop-runner :as runner]
            [futon2.aif.hermetic-repair-fixture :as hermetic] [futon2.aif.learning-trial-ledger :as learning-ledger]
            [futon2.aif.policy :as policy] [futon2.aif.trace :as trace]
            [futon3c.diagramprover.wm-wire-r9-support :as r9-support] [futon3c.diagramprover.wm-wire :as w])
  (:import [java.security MessageDigest]))
(defn- step [id] {:id id :target "M-t" :guard {:clauses [{:present #{} :absent #{}}]} :produces #{}})
(defn- ranked [cid pattern g rank] {:action {:kind :cascade-candidate :id cid :cascade-id cid :target "M-t" :precedence [(step pattern)] :construction-receipt {:kind :fixture} :interpretation-receipts {cid {:kind :fixture}}} :cascade true :cascade-id cid :controller-score g :rank rank})
(def roster [(ranked :cas/b :p/b 1.0 1) (ranked :cas/a :p/a 3.0 2)])
(def roster-other [(ranked :cas/a :p/a 1.0 1) (ranked :cas/b :p/b 3.0 2)])
(defn- opts [decision] (merge (hermetic/runner-repair-options) r9-support/hermetic-runner-defaults {:cohort? false :author "zai-5" :reviewer "codex-7" :repair-reviewer "codex-1" :phase-log-fn (fn [_]) :roster-fn (fn [_] {:zai-5 {:status "idle" :invoke-ready? true} :codex-7 {:status "idle" :invoke-ready? true} :codex-1 {:status "idle" :invoke-ready? true}}) :refresh-fn (fn []) :substrate-preflight-fn (fn [_] {:route :test}) :code-state-fn (fn [] {:repo "/futon2" :git-sha "head" :git-dirty? false :repo-heads {}}) :mode-flags-fn (fn [] {}) :version-stamp-fn identity :mission-fn (fn [t] {:id t}) :repair-open-fn (constantly []) :repair-system-record-fn (fn [m] {:repair/id "repair-wire-1" :repair/class (:repair-class m)}) :r16-park-fn (fn [_ _] {:ok true :id "park-wire" :status :parked}) :delivery-qa-fn (fn [_ _] {:morning-brief/addendum-id "qa-wire"}) :queue-fn identity :judge-fn (fn [_] {:judgement {:decision decision :belief {} :belief-pre {} :observation {} :free-energy {} :prediction-errors {} :precision-state {} :micro-step-trace [] :mode :maintain}}) :construct-fn (fn [& _] (throw (ex-info "stop" {:outcome :incomplete})))}))
(defn- run-record [xs] (let [d (policy/select-action-cascades xs {:beta 1 :novelty-inputs {}})] (with-redefs-fn {#'trace/default-trace-dir (w/tmp-dir "wire-trace") #'runner/default-run-record-dir (w/tmp-dir "wire-run-records") #'learning-ledger/default-root (w/tmp-dir "wire-learning")} #(binding [runner/*wm-status-reporting?* false] (edn/read-string (slurp (:run-record (runner/run-opportunity! (opts d)))))))))
(defn observe ([xs] (observe xs "M-t")) ([xs target] (let [r (run-record xs) s (fr/record-summary target "click-1" r) e (first (:clicks (flight/record-click (flight/start {:target target :chosen-because {:kind :requested}} {:kind :a-exits :repo "futon3c" :path "p" :read-text (fn [& _] "")} {:id "flight-wire"}) (merge s {:wants [:t/b] :before {} :after {}}))))] {:writer (:chosen s) :reader (if (contains? e :chosen) (:chosen e) {:absent :field-not-carried}) :record-chosen (get-in r [:decision :chosen]) :reader-agrees? (and (= (get-in r [:decision :chosen :candidate]) (get-in e [:chosen :candidate])) (= (get-in r [:decision :chosen :precedence]) (get-in e [:chosen :precedence])))})))
(defn build-record [] (let [p (observe roster) a (observe roster "M-some-other-target") d (observe roster-other)] {:producer 'futon3c.diagramprover.wm-wire-producer-wm-wire-flight-record-summary-flight-click-close-test-chosen-test :operation ['futon2.aif.full-loop-runner/run-opportunity! 'futon2.aif.flight-runner/record-summary 'futon2.aif.flight/record-click] :inputs {:rosters [:cas-b-first :cas-a-first] :targets ["M-t" "M-some-other-target"]} :fields {:positive p :absent a :different d} :left-out {:temporary-stores "isolated trace, run-record, and learning stores"}}))
(defn- text [x] (str (pr-str x) "\n"))
(defn- sha [s] (apply str (map #(format "%02x" (bit-and % 255)) (.digest (MessageDigest/getInstance "SHA-256") (.getBytes s "UTF-8")))))
(defn- leaves [x] (letfn [(f [p v] (if (map? v) (mapcat (fn [[k x]] (f (conj p k) x)) v) [p]))] (f [] x)))
(defn- write! [x] (let [s (text x) f (io/file "test/fixtures/wire-producers" (str "wm-wire-flight-record-summary-flight-click-close-test-chosen@" (subs (sha s) 0 12) ".edn"))] (when (.exists f) (throw (ex-info "exists" {}))) (spit f s) (println f)))
(deftest producer-test (let [a (build-record)] (if (= "1" (System/getenv "WM_WIRE_PRODUCER_WRITE")) (write! a) (let [f (first (filter #(.startsWith (.getName %) "wm-wire-flight-record-summary-flight-click-close-test-chosen@") (.listFiles (io/file "test/fixtures/wire-producers")))) e (edn/read-string (slurp f))] (doseq [p (leaves (:fields e))] (testing (pr-str p) (is (= (get-in e (into [:fields] p)) (get-in a (into [:fields] p))))))))))
