(ns futon3c.diagramprover.wm-wire-everything-loads-test
  "One whole-file-rule sentinel for the product namespaces loaded by wire tests."
  (:require [clojure.java.io :as io]
            [clojure.string :as str]
            [clojure.test :refer [deftest is testing]]))

(def product-namespaces
  '[
    futon.flexiarg.projection
    futon.notions
    futon.text
    futon1b-harness
    futon1b-origin
    futon2.aif.accepted-increment
    futon2.aif.accumulation-bmr
    futon2.aif.action-identity
    futon2.aif.action-proposer
    futon2.aif.anticipation
    futon2.aif.attempt-learning
    futon2.aif.belief
    futon2.aif.beta-habit
    futon2.aif.bmr
    futon2.aif.c-fold-config
    futon2.aif.c-vector
    futon2.aif.calibration-admission
    futon2.aif.calibration-cycle
    futon2.aif.candidate-derivations
    futon2.aif.cascade-equivalence
    futon2.aif.cascade-free-energy
    futon2.aif.cascade-habit-reinforcement
    futon2.aif.cascade-habit-store
    futon2.aif.cascade-model-manifest
    futon2.aif.cascade-observation-scoring
    futon2.aif.cascade-plan
    futon2.aif.cascade-policy
    futon2.aif.cascade-prior
    futon2.aif.cascade-problems
    futon2.aif.cascade-proposals
    futon2.aif.cascade-selection
    futon2.aif.cascade-sources
    futon2.aif.cascade-structure
    futon2.aif.check-candidates
    futon2.aif.close-loop
    futon2.aif.close-retention
    futon2.aif.conditioned-trajectory
    futon2.aif.construction
    futon2.aif.construction-moves
    futon2.aif.controller-authority
    futon2.aif.d-predecessor-task-authority
    futon2.aif.decision-gate
    futon2.aif.delivery-qa
    futon2.aif.disposition-risk
    futon2.aif.efe
    futon2.aif.enactment-fold-source
    futon2.aif.enactment-habit
    futon2.aif.enumeration-completeness
    futon2.aif.epistemic-value
    futon2.aif.evidence-manifest
    futon2.aif.exact-belief-adapter
    futon2.aif.exact-belief-core
    futon2.aif.fact-measurement
    futon2.aif.find-designation
    futon2.aif.find-expectations
    futon2.aif.find-receipt
    futon2.aif.finding-ticket
    futon2.aif.flight
    futon2.aif.flight-driver
    futon2.aif.flight-runner
    futon2.aif.focus-receipt
    futon2.aif.fold
    futon2.aif.fold-cascade
    futon2.aif.fold-classical
    futon2.aif.fold-eval
    futon2.aif.fold-llm
    futon2.aif.fold-semilattice
    futon2.aif.forward-model
    futon2.aif.free-energy
    futon2.aif.full-loop-cohort
    futon2.aif.full-loop-runner
    futon2.aif.g-term-decomposition
    futon2.aif.grain-gate
    futon2.aif.habit-prior
    futon2.aif.hierarchical-budget
    futon2.aif.increment-attestation
    futon2.aif.interoceptive-store-lock
    futon2.aif.interpretation-construction
    futon2.aif.interpretation-evidence
    futon2.aif.interpretation-job
    futon2.aif.interpretation-request
    futon2.aif.intrinsic-values
    futon2.aif.job-text-retention
    futon2.aif.kernel-example
    futon2.aif.lane-futility
    futon2.aif.learning-trial
    futon2.aif.learning-trial-ledger
    futon2.aif.lifecycle-exits
    futon2.aif.likelihood-precision
    futon2.aif.limb-evidence
    futon2.aif.live-c
    futon2.aif.load-identity
    futon2.aif.loaded-displacement
    futon2.aif.machine-accumulation
    futon2.aif.machine-model
    futon2.aif.machine-q
    futon2.aif.machine-q-risk
    futon2.aif.matched-observation-evidence
    futon2.aif.memory-contract
    futon2.aif.mission-c
    futon2.aif.mission-criteria
    futon2.aif.mission-epistemic-value
    futon2.aif.mission-gauges
    futon2.aif.mission-hole-wants
    futon2.aif.mission-reading
    futon2.aif.mission-registry
    futon2.aif.morning-brief
    futon2.aif.move-class-intensity
    futon2.aif.observation
    futon2.aif.observation-admission
    futon2.aif.observation-checks
    futon2.aif.observation-label-reader
    futon2.aif.observation-label-store
    futon2.aif.observation-label-wire
    futon2.aif.observation-labels
    futon2.aif.observation-model
    futon2.aif.observation-rates
    futon2.aif.outer-cascade
    futon2.aif.outer-loop
    futon2.aif.parameter-novelty
    futon2.aif.pattern-registry
    futon2.aif.policy
    futon2.aif.policy-depth
    futon2.aif.policy-free-energy
    futon2.aif.policy-precision
    futon2.aif.policy-precision-carry
    futon2.aif.policy-prefix-admission
    futon2.aif.policy-prefix-evidence
    futon2.aif.precision
    futon2.aif.preference-audit
    futon2.aif.preference-module
    futon2.aif.preferences
    futon2.aif.realized-outcome
    futon2.aif.realized-recording
    futon2.aif.receipt-construction
    futon2.aif.registry-port
    futon2.aif.repair-discharge
    futon2.aif.repair-discharge-evidence
    futon2.aif.repair-discharge-receipt
    futon2.aif.repair-evaluators
    futon2.aif.repair-history-replay
    futon2.aif.repair-obligation
    futon2.aif.repair-proposals
    futon2.aif.rollout
    futon2.aif.route-attestation
    futon2.aif.ruled-outcome-c
    futon2.aif.run-ending-classification
    futon2.aif.run-participants
    futon2.aif.run4-task-pin
    futon2.aif.scan-report
    futon2.aif.scoring-input-receipts
    futon2.aif.selection-gain
    futon2.aif.selection-rationale
    futon2.aif.served-by-reading
    futon2.aif.shadow-cascade-g
    futon2.aif.sorry-registry
    futon2.aif.strategic-habit
    futon2.aif.substrate
    futon2.aif.surprise
    futon2.aif.target-field
    futon2.aif.task-belief-ladder
    futon2.aif.task-execution-evidence
    futon2.aif.temporal-input
    futon2.aif.temporal-update
    futon2.aif.ticket-publication-io
    futon2.aif.ticket-queue
    futon2.aif.token-belief-carry
    futon2.aif.token-belief-predecessor
    futon2.aif.token-initialization-policy
    futon2.aif.token-outcome
    futon2.aif.token-outcome-pair
    futon2.aif.trace
    futon2.aif.tripwire
    futon2.aif.want-interpretation
    futon2.aif.wm.cascade-decision
    futon2.aif.wm.construction-inputs
    futon2.aif.zeta-posterior
    futon2.report.cascade-lane
    futon2.report.war-machine
    futon2.wm-trigger
    futon2.wm.extract-outcomes
    futon3.gate.auth
    futon3.gate.errors
    futon3.gate.evidence
    futon3.gate.exec
    futon3.gate.pattern
    futon3.gate.pipeline
    futon3.gate.shapes
    futon3.gate.task
    futon3.gate.util
    futon3.gate.validate
    futon3.inbox-zero.projection
    futon3.inbox-zero.state
    futon3b.query.relations
    futon3b.query.transcript
    futon3c.agency.act-harness
    futon3c.agency.agent-pouch
    futon3c.agency.atomic-file
    futon3c.agency.bell-router
    futon3c.agency.clock-decision
    futon3c.agency.clock-lineage
    futon3c.agency.clock-store
    futon3c.agency.federation
    futon3c.agency.followup-queue
    futon3c.agency.frame-seats
    futon3c.agency.inbox
    futon3c.agency.invariants
    futon3c.agency.invoke-activity
    futon3c.agency.invoke-controls
    futon3c.agency.invoke-ingress-controller
    futon3c.agency.job-tree
    futon3c.agency.mesh-qa
    futon3c.agency.parked-on
    futon3c.agency.pattern-card-acts
    futon3c.agency.pattern-card-provider
    futon3c.agency.pattern-card-record
    futon3c.agency.pattern-card-record-cli
    futon3c.agency.promise-capture
    futon3c.agency.promise-history
    futon3c.agency.promise-outcome
    futon3c.agency.promise-record
    futon3c.agency.prompt-line
    futon3c.agency.registry
    futon3c.agency.roles
    futon3c.agency.rule-record
    futon3c.agency.rule-timeline
    futon3c.agency.turn-queue
    futon3c.agency.warrant
    futon3c.agents.kimi-api
    futon3c.agents.memory-provisioning
    futon3c.agents.tickle
    futon3c.agents.zai-api
    futon3c.agents.zaif-controller
    futon3c.agents.zaif-inputs
    futon3c.aif.live-recommendation
    futon3c.aif.mission-head
    futon3c.aif.observe
    futon3c.apm.authority-port
    futon3c.apm.campaign-machine
    futon3c.apm.campaign-trace
    futon3c.apm.conductor
    futon3c.apm.conductor-binding
    futon3c.apm.conductor-open
    futon3c.apm.conductor-surface
    futon3c.apm.cycle-harness
    futon3c.apm.frame-cycle-contract
    futon3c.apm.generated-contract
    futon3c.apm.job-port
    futon3c.apm.job-state
    futon3c.apm.library-loop-checkpoint
    futon3c.apm.library-loop-runner
    futon3c.apm.live-preflight
    futon3c.apm.live-preflight-runtime
    futon3c.apm.memory-access-gate
    futon3c.apm.memory-caption-store
    futon3c.apm.preregistration
    futon3c.apm.promotion-pipeline
    futon3c.apm.role-memory-search
    futon3c.apm.toolchain-port
    futon3c.apm.typed-role-submission
    futon3c.blackboard
    futon3c.bridge
    futon3c.cyder
    futon3c.dev.config
    futon3c.dispatch-with-recall
    futon3c.enrichment.query
    futon3c.evidence.backend
    futon3c.evidence.boundary
    futon3c.evidence.futon1b-backend
    futon3c.evidence.http-backend
    futon3c.evidence.invariant
    futon3c.evidence.origin
    futon3c.evidence.store
    futon3c.evidence.subject
    futon3c.inbox-zero.followup-validity
    futon3c.inbox-zero.sweeper
    futon3c.marks
    futon3c.mfuton-mode
    futon3c.mission-control.service
    futon3c.peripheral.alfworld
    futon3c.peripheral.arse
    futon3c.peripheral.chat
    futon3c.peripheral.common
    futon3c.peripheral.cycle
    futon3c.peripheral.deploy
    futon3c.peripheral.discipline
    futon3c.peripheral.edit
    futon3c.peripheral.emacs-cursor
    futon3c.peripheral.evidence
    futon3c.peripheral.explore
    futon3c.peripheral.memory-backend
    futon3c.peripheral.memory-lifecycle
    futon3c.peripheral.memory-recall
    futon3c.peripheral.memory-write
    futon3c.peripheral.mentor
    futon3c.peripheral.mentor-map
    futon3c.peripheral.mission
    futon3c.peripheral.mission-backend
    futon3c.peripheral.mission-control
    futon3c.peripheral.mission-control-backend
    futon3c.peripheral.mission-shapes
    futon3c.peripheral.night-shift
    futon3c.peripheral.night-shift-backend
    futon3c.peripheral.night-shift-shapes
    futon3c.peripheral.problem
    futon3c.peripheral.proof
    futon3c.peripheral.proof-backend
    futon3c.peripheral.proof-dag
    futon3c.peripheral.proof-shapes
    futon3c.peripheral.pull-receipts
    futon3c.peripheral.real-backend
    futon3c.peripheral.reflect
    futon3c.peripheral.registry
    futon3c.peripheral.runner
    futon3c.peripheral.test-runner
    futon3c.peripheral.tools
    futon3c.portfolio.adjacent
    futon3c.portfolio.affect
    futon3c.portfolio.core
    futon3c.portfolio.heartbeat
    futon3c.portfolio.logic
    futon3c.portfolio.observe
    futon3c.portfolio.perceive
    futon3c.portfolio.policy
    futon3c.reflection.core
    futon3c.reflection.envelope
    futon3c.social.bells
    futon3c.social.coordination-ledger
    futon3c.social.dispatch
    futon3c.social.mode
    futon3c.social.peripheral
    futon3c.social.persist
    futon3c.social.presence
    futon3c.social.shapes
    futon3c.social.whistles
    futon3c.substrate.client
    futon3c.substrate.read-health
    futon3c.test-registry
    futon3c.test-registry.currentness
    futon3c.test-registry.ledger
    futon3c.test-registry.local-port
    futon3c.test-registry.local-store
    futon3c.test-registry.sqlite-backend
    futon3c.transport.encyclopedia
    futon3c.transport.http
    futon3c.transport.peripheral-events
    futon3c.transport.protocol
    futon3c.transport.ws.invoke
    futon3c.util.cwd
    futon3c.watcher.roots
    futon3c.wm.machinery-execution-cohort
    futon3c.wm.ordinary-click-budget
    futon3c.wm.run4-attempt-admission
    futon3c.wm.run4-effective-environment
    futon3c.wm.run4-execution-cohort
    futon3c.wm.run4-historical-action
    futon3c.wm.run4-historical-projection
    futon3c.wm.run4-historical-successor
    futon3c.wm.run4-pinned-run-config
    futon3c.wm.run4-realized-recording
    futon3c.wm.run4-run-visibility
    futon3c.wm.run4-series-controller
    futon3c.wm.run4-series-service
    futon3c.wm.run4-terminal-evidence
    futon3c.wm.run4-terminal-projection
    futon3c.wm.run4-trusted-entry
    futon3c.wm.runner-service
    meme.arrow
    meme.core
    meme.fold
    meme.gates
    meme.schema
    meme.step
    sidecar.store
    sidecar.validation
    ])

(defn- source-resource
  [namespace]
  (let [stem (-> (str namespace)
                 (str/replace "." "/")
                 (str/replace "-" "_"))]
    (or (io/resource (str stem ".clj"))
        (io/resource (str stem ".cljc")))))

(deftest every-product-namespace-loads
  (doseq [namespace product-namespaces]
    (testing (str namespace)
      (try
        (require namespace)
        (is (some? (find-ns namespace))
            (str "namespace did not load: " namespace))
        (catch Throwable error
          (is false
              (str "namespace failed to load: " namespace ": "
                   (or (.getMessage error) (class error)))))))))

(deftest namespace-list-is-unique-and-resolvable
  (is (= (count product-namespaces) (count (set product-namespaces)))
      "the literal namespace vector has no duplicates")
  (doseq [namespace product-namespaces]
    (testing (str namespace)
      (is (some? (source-resource namespace))
          (str "no .clj or .cljc source resource for " namespace)))))
