(ns futon3c.diagramprover.wm-wire-producer-wm-wire-flight-run-flight-driver-summary-needs-test-literal--test
  (:require [clojure.edn :as edn] [clojure.java.io :as io] [clojure.test :refer [deftest is testing]] [futon2.aif.flight-driver :as fd] [futon3c.diagramprover.wm-wire :as w])
  (:import [java.security MessageDigest]))
(def producer 'futon3c.diagramprover.wm-wire-producer-wm-wire-flight-run-flight-driver-summary-needs-test-literal--test)
(def operation ['futon2.aif.flight-driver/run-flight! 'futon2.aif.flight/run!])
(def wire-id [:flight-run :flight-driver-summary :needs])
(def mission-text "A mission text with no recognised criteria.\n")
(defn- observe [abstain?] (let [result (fd/run-flight! {:target "M-wire-driver" :repo "futon3c" :path "holes/missions/M-wire.md" :read-text (fn [& _] mission-text) :store (w/tmp-dir "wire-store") :run-record-dir (w/tmp-dir "wire-run-records") :sources {} :answer-fn (fn [_] {:state "declined" :seat "wire-seat" :job-id "wire-job-1"}) :max-clicks 1 :click-fn (fn [_] (cond-> {:click-id "wire-click-1" :unreached-wants []} abstain? (assoc :abstention {:kind :click-not-started :missing :click :status 409 :detail {:error "refused"}})))} {:flight-id "flight-wire-driver"})] {:writer (:needs (:flight result)) :reader (:needs result) :status (:status result)}))
(defn build-record [] {:producer producer :operation operation :inputs {:mission-text mission-text :max-clicks 1 :flight-id "flight-wire-driver"} :wires {wire-id {:primary (observe false) :different (observe true)}} :left-out {:temporary-paths "fresh hermetic store and run-record directories"}})
(def stem "wm-wire-flight-run-flight-driver-summary-needs-test-literal-")
(defn- text [x] (str (pr-str x) "\n"))
(defn- sha [s] (apply str (map #(format "%02x" (bit-and % 255)) (.digest (MessageDigest/getInstance "SHA-256") (.getBytes s "UTF-8")))))
(defn- files [] (filter #(.startsWith (.getName %) (str stem "@")) (.listFiles (io/file "test/fixtures/wire-producers"))))
(defn- write! [r] (let [s (text r) f (io/file "test/fixtures/wire-producers" (str stem "@" (subs (sha s) 0 12) ".edn"))] (when (.exists f) (throw (ex-info "record exists" {}))) (spit f s) (println f)))
(defn- leaves [x] (letfn [(walk [p v] (if (map? v) (mapcat (fn [[k z]] (walk (conj p k) z)) v) [p]))] (walk [] x)))
(deftest producer-test (let [a (build-record)] (if (= "1" (System/getenv "WM_WIRE_PRODUCER_WRITE")) (write! a) (let [fs (files)] (is (= 1 (count fs))) (let [e (edn/read-string (slurp (first fs)))] (doseq [p (leaves e)] (testing (pr-str p) (is (= (get-in e p) (get-in a p))))))))))
