#!/usr/bin/env bb
;; WM-COVERAGE-FILE-I: exercise the real generator against committed inputs and
;; explicit snapshots. Nothing under the repository is regenerated by this test.
(ns wm-coverage-file-test
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.java.shell :as sh]
            [clojure.string :as str]
            [clojure.test :refer [deftest is run-tests]]))

(def repo (str (System/getProperty "user.home") "/code/futon3c"))
(def lab "holes/labs/M-wm-wiring/")
(def generator (str repo "/" lab "spike/wm_coverage.bb"))
(def revision
  (let [r (sh/sh "git" "-C" repo "rev-parse" "HEAD")]
    (assert (zero? (:exit r)) (:err r))
    (str/trim (:out r))))

(defn committed [name]
  (let [r (sh/sh "git" "-C" repo "show" (str revision ":" lab name))]
    (assert (zero? (:exit r)) (:err r))
    (:out r)))

(defn sha256 [text]
  (apply str
         (map #(format "%02x" (bit-and 255 %))
              (.digest (java.security.MessageDigest/getInstance "SHA-256")
                       (.getBytes text java.nio.charset.StandardCharsets/UTF_8)))))

(defn generate [ledger org output]
  (sh/sh "bb" generator ledger org
         :env (cond-> (dissoc (into {} (System/getenv))
                             "WM_COVERAGE_OUT" "WM_COVERAGE_FIRST_PATH_ONLY")
                output (assoc "WM_COVERAGE_OUT" output))))

(defn read-output [result path]
  (is (zero? (:exit result)) (:err result))
  (when (zero? (:exit result)) (edn/read-string (slurp path))))

(deftest explicit-snapshot-and-publication-boundary
  (let [dir (.toFile (java.nio.file.Files/createTempDirectory
                     "wm-coverage-file-" (make-array java.nio.file.attribute.FileAttribute 0)))
        path #(str (io/file dir %))
        ledger-text (committed "wm-wire-ledger.edn")
        org-text (committed "wm-org-layer.edn")
        ledger-file (path "ledger.edn")
        org-file (path "org.edn")
        canonical (str repo "/" lab "wm-wire-coverage.edn")
        before (slurp canonical)]
    (try
      (spit ledger-file ledger-text)
      (spit org-file org-text)
      (let [by-rev (read-output (generate revision revision (path "revision.edn")) (path "revision.edn"))
            by-file (read-output (generate ledger-file org-file (path "file.edn")) (path "file.edn"))]
        (is (= (dissoc by-rev :inputs) (dissoc by-file :inputs))
            "same bytes yield the same partition; only input provenance changes")
        (is (true? (get-in by-file [:inputs :ledger :uncommitted-input])))
        (is (= (sha256 ledger-text) (get-in by-file [:inputs :ledger :sha256])))
        (is (= (sha256 org-text) (get-in by-file [:inputs :org-layer :sha256])))
        (is (nil? (get-in by-rev [:inputs :ledger :uncommitted-input]))))
      ;; A file that differs from HEAD must actually be the input, not an ignored
      ;; option or an alias for the default ledger. Retain a real wire and map pin.
      (let [ledger (edn/read-string ledger-text)
            wire (first (:wires ledger))
            changed (pr-str (assoc ledger :wires [wire] :counts {:wires 1}))]
        (spit ledger-file changed)
        (let [result (read-output (generate ledger-file revision (path "one.edn")) (path "one.edn"))]
          (is (= [(:wire wire)] (mapv :wire (:wires result))))
          (is (= 1 (get-in result [:counts :wires])))
          (is (= (sha256 changed) (get-in result [:inputs :ledger :sha256])))))
      (doseq [[ledger org output] [[ledger-file revision nil]
                                   [revision org-file nil]
                                   [ledger-file revision canonical]
                                   [ledger-file revision ledger-file]
                                   [revision org-file org-file]]]
        (let [result (generate ledger org output)]
          (is (not (zero? (:exit result))) "file input cannot replace canonical coverage or itself")
          (is (str/includes? (:err result) "wm_coverage:"))))
      (is (= before (slurp canonical)) "every run left canonical coverage untouched")
      (is (= org-text (slurp org-file)) "input preservation is checked, not inferred from exit")
      (finally
        (doseq [f (reverse (file-seq dir))] (io/delete-file f))))))

(let [result (run-tests)]
  (when (pos? (+ (:fail result) (:error result))) (System/exit 1)))
