#!/usr/bin/env bb
;; JOIN-2B-I (E-kimi-task-78): exercise wm_vs_equation_dag.bb's <2>2b
;; inventory classes against small fixtures (pattern:
;; spike/wm_coverage_file_test.clj). Nothing under the repository is
;; regenerated by this test.
(ns wm-vs-equation-dag-inventory-test
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.java.shell :as sh]
            [clojure.test :refer [deftest is run-tests]]))

(def repo (str (System/getProperty "user.home") "/code/futon3c"))
(def generator (str repo "/holes/labs/M-wm-wiring/spike/wm_vs_equation_dag.bb"))

;; Fixture registry. Theory edges: RA->RB (s-a into eq-b), RA->RC and RB->RC
;; (s-a, s-b into eq-c), RA->RD (s-a into eq-d). One edge per inventory class:
;; RB->RC is declared by-var AND named in :holes (declared wins); RA->RD is a
;; :holes edge; RA->RC is named by eq-c's CODE-PATH NOTE; RA->RB is none -- the
;; :holes entry [:RB :RA] names the REVERSED edge and must not classify it.
(def fixture-registry
  {:as-of "fixture"
   :equations [{:equation :eq-a :defines :s-a0 :imports [] :node :RA
                :code nil}
               {:equation :eq-b :defines :s-b :imports [:s-a] :node :RB
                :code "futon2 src/futon2/aif/b.clj:1 (make-b)"}
               {:equation :eq-c :defines :s-c :imports [:s-a :s-b] :node :RC
                :code (str "futon2 src/futon2/aif/c.clj:1 (make-c). "
                           "CODE-PATH NOTE for [:RA :RC] (FIXTURE-D): s-a does NOT enter "
                           "RC directly -- it reaches RC through RB's update, i.e. through s-b.")}
               {:equation :eq-d :defines :s-d :imports [:s-a] :node :RD
                :code "futon2 src/futon2/aif/d.clj:1 (make-d)"}
               {:equation :eq-retired :defines :s-x :imports [:s-a] :node :RX
                :code "x.clj (make-x)" :status :retired}]
   :exogenous [{:symbol :s-a :node :RA}]
   :holes [{:edges [[:RB :RC]] :equation :eq-c :status :not-realised
            :finding "declared by-var; declared must win"}
           {:edge [:RA :RD] :equation :eq-d :status :path-dependent
            :finding "a hole edge"}
           {:edge [:RB :RA] :equation :eq-b :status :not-realised
            :finding "the REVERSED edge; must not classify RA->RB"}
           {:edge [:RA :RZ] :equation :eq-d :status :not-realised
            :finding "names an edge not in the DAG; must be reported"}
           {:symbol :F :status :no-consumer :finding "not an edge; ignored"}]})

(def fixture-map
  {:boxes [{:box/id :box-b :box/kind :code
            :site {:file "src/futon2/aif/b.clj" :var "make-b"}
            :writes [:f] :reads []}
           {:box/id :box-c :box/kind :code
            :site {:file "src/futon2/aif/c.clj" :var "make-c"}
            :writes [] :reads [:f]}]})

(def fixture-correspondence
  [{:edge [:RB :RC] :term :s-b :field :f :grain :field
    :provenance "fixture writer make-b to reader make-c"}])

(defn generate
  ([map-file registry-file] (generate map-file registry-file fixture-correspondence))
  ([map-file registry-file entries]
   (let [table-file (io/file (.getParentFile (io/file map-file)) "terms.edn")]
     (spit table-file (pr-str entries))
     (sh/sh "bb" generator
            :env (assoc (into {} (System/getenv))
                        "WM_VS_DAG_MAP_FILE" (str map-file)
                        "WM_VS_DAG_REGISTRY_FILE" (str registry-file)
                        "WM_VS_DAG_TERM_FIELDS_FILE" (str table-file))))))

(deftest inventory-classes
  (let [dir (.toFile (java.nio.file.Files/createTempDirectory
                      "wm-vs-dag-inventory-" (make-array java.nio.file.attribute.FileAttribute 0)))
        map-file (io/file dir "map.edn")
        registry-file (io/file dir "registry.edn")]
    (try
      (spit map-file (pr-str fixture-map))
      (spit registry-file (pr-str fixture-registry))
      (let [result (generate map-file registry-file)]
        (is (zero? (:exit result)) (:err result))
        (let [out (edn/read-string (:out result))
              by-edge (into {} (map (fn [e] [(:edge e) e]) (:edges out)))]
          (is (= (str map-file) (:map out)) "fixture map provenance recorded")
          (is (= (str registry-file) (:registry-rev out)) "fixture registry provenance recorded")
          (is (= 4 (:theory-edges out)) "the retired equation contributes no edge")
          (is (= :declared (get-in by-edge [[:RB :RC] :inventory]))
              "RB->RC is declared by-var AND a hole; declared wins")
          (is (nil? (get-in by-edge [[:RB :RC] :hole-status]))
              "a declared edge carries no hole status")
          (is (= :hole (get-in by-edge [[:RA :RD] :inventory])))
          (is (= :path-dependent (get-in by-edge [[:RA :RD] :hole-status]))
              "the hole entry's :status is carried")
          (is (= :code-path-note (get-in by-edge [[:RA :RC] :inventory]))
              "the CODE-PATH NOTE marker in eq-c's :code classifies RA->RC")
          (is (= :none (get-in by-edge [[:RA :RB] :inventory]))
              "bad case: the hole naming the REVERSED edge [:RB :RA] does not classify RA->RB")
          (is (= {:declared 1 :hole 1 :code-path-note 1 :none 1}
                 (:summary-inventory out)))
          (is (= [[:RA :RB]] (:inventory-none out)))
          (is (= [[:RA :RZ] [:RB :RA]] (:holes-not-in-dag out))
              "holes naming edges not in the DAG are reported, not silently ignored")))
      (finally
        (doseq [f (reverse (file-seq dir))] (io/delete-file f))))))

(deftest field-credit-must-cover-every-term
  (let [dir (.toFile (java.nio.file.Files/createTempDirectory
                      "wm-term-fields-" (make-array java.nio.file.attribute.FileAttribute 0)))
        map-file (io/file dir "map.edn")
        registry-file (io/file dir "registry.edn")
        base (first fixture-correspondence)]
    (try
      (spit map-file (pr-str fixture-map))
      (doseq [[label entries two-terms? expected uncovered]
              [[:matching [base] false :declared #{}]
               [:wrong-term [(assoc base :term :want)] false :does-not-carry #{:s-b}]
               [:no-entry [] false :cannot-tell #{:s-b}]
               [:record-grain [(assoc base :grain :record)] false :declared #{}]
               [:identity [(assoc base :identity "s-b := value at f")] false :declared #{}]
               [:partial [base] true :does-not-carry #{:s-b2}]
               [:foreign-edge [(assoc base :edge [:RA :RC])] false :cannot-tell #{:s-b}]
               [:uncredited-field [(assoc base :field :other)] false :cannot-tell #{:s-b}]]]
        (let [reg (if two-terms?
                    (-> fixture-registry
                        (update :equations conj {:defines :s-b2 :node :RB :imports []})
                        (update-in [:equations 2 :imports] conj :s-b2))
                    fixture-registry)]
          (spit registry-file (pr-str reg))
          (let [{:keys [exit out err]} (generate map-file registry-file entries)]
            (is (zero? exit) (str label ": " err))
            (let [result (edn/read-string out)
                  edge (first (filter #(= [:RB :RC] (:edge %)) (:edges result)))]
              (is (= :declared (:by-var edge)) (str label " retains raw field credit"))
              (is (= expected (:inventory edge)) (str label))
              (is (= uncovered (get-in edge [:term-coverage :uncovered])) (str label))
              (when (#{:does-not-carry :cannot-tell} expected)
                (is (= [[:RB :RC]] (get result (keyword (str "inventory-" (name expected)))))
                    (str label " listed independently of inventory-none")))))))
      (finally
        (doseq [f (reverse (file-seq dir))] (io/delete-file f))))))

(let [result (run-tests)]
  (when (pos? (+ (:fail result) (:error result))) (System/exit 1)))
