#!/usr/bin/env python3
"""enumerate_sites.py — instance 4's counting step (or3/count-every-card-back).

Lists every site in futon3c src/ that names a provider seat as a string
literal, and every site that decides by provider. Writes sites.edn beside this
file. Run from /home/joe/code/futon3c. Deterministic for a fixed tree.
"""
import os, re, subprocess
SEAT = re.compile(r'"((?:oxf-|lon-|chi-)?(?:claude|codex|kimi|zai)-\d+)"')
ROUTE = [(re.compile(r'starts-with\?.*"(claude|codex|kimi|zai)"'), "id-prefix"),
         (re.compile(r'\(=\s*"(codex|claude|kimi|zai)"\s*\(\.getName'), "command-binary-name")]
rev = subprocess.check_output(["git", "rev-parse", "--short=8", "HEAD"], text=True).strip()
seats, routes = [], []
for root, _, files in os.walk("src"):
    for f in sorted(files):
        if not f.endswith((".clj", ".cljc")): continue
        p = os.path.join(root, f)
        for n, line in enumerate(open(p, encoding="utf-8"), 1):
            code = line.split(";", 1)[0]
            for m in SEAT.finditer(code):
                seats.append((p, n, m.group(1)))
            for rx, kind in ROUTE:
                if rx.search(code): routes.append((p, n, kind))
seats.sort(); routes.sort()
q = lambda s: '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'
out = [";; Generated by enumerate_sites.py; do not edit.",
       "{:schema :m-futon-seams/sites-v1 :tree-rev %s" % q(rev),
       " :seat-literals-count %d :seat-literal-files %d" % (len(seats), len({s[0] for s in seats})),
       " :routing-sites [" + " ".join("{:path %s :line %d :kind :%s}" % (q(p), n, k) for p, n, k in routes) + "]",
       " :seat-literals ["]
out += ["  {:path %s :line %d :seat %s}" % (q(p), n, q(s)) for p, n, s in seats]
out += [" ]}"]
open(os.path.join(os.path.dirname(__file__), "sites.edn"), "w").write("\n".join(out) + "\n")
print("seat literals", len(seats), "in", len({s[0] for s in seats}), "files; routing sites", routes)
