#!/usr/bin/env python3
"""Regenerate holes/labs/M-codex-sorry-loop/surface-payoff.edn from the receipts.

WHY THIS EXISTS (2026-07-30). Joe asked for payoff-per-search-surface to be
tracked. The ledger was hand-maintained and went stale after run 8, while the
same fields (:arm-that-paid, :arm-tried-and-empty, :not-needed, :arxiv-verdict)
kept being written into every run receipt. The receipts are the authoritative
record; the ledger is a PROJECTION of them, so it should be generated, not
typed. Hand-maintaining a projection is how it rots.

Receipt ids are read from the ⊸ register (holes/ops/claude-6.md), which is where
every run's receipt id is stated at the time it is written, and fetched BY ID —
the store's fast path (~0.18 s), not the list path (2-24 s, see
docs/xtdb2-memory-latency-2026-07-30.md).

Receipts predating the ledger carry no arm fields. Those are NOT silently
dropped: they are listed under :receipts-without-arm-data so the ledger's
coverage is legible rather than implied.

Usage:  build_surface_payoff.py [--commit]
Default is a dry run printing the row count and the skip list.
"""
from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path

from edn_format import loads, Keyword as K

FUTON3C = Path(__file__).resolve().parent.parent
REGISTER = FUTON3C / "holes/ops/claude-6.md"
LEDGER = FUTON3C / "holes/labs/M-codex-sorry-loop/surface-payoff.edn"
STORE = "http://127.0.0.1:7073/api/alpha/evidence"

RECEIPT_RE = re.compile(r"receipt ([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})")

# Fields lifted from the receipt's :outcome into a ledger row, in ledger order.
CARRY = [
    "problem", "declarations", "classification", "standard-result",
    "arm-that-paid", "arm-tried-and-empty", "arxiv-arm-entered", "arxiv-verdict",
    "route-source", "metric-3-memories-surfaced", "metric-3-memories-used",
    "problems-closed-today", "commit",
]


def fetch(rid: str) -> dict | None:
    try:
        with urllib.request.urlopen(f"{STORE}/{rid}", timeout=60) as r:
            return loads(r.read().decode())
    except Exception as exc:  # noqa: BLE001
        print(f"  {rid[:8]} FETCH FAILED: {exc}", file=sys.stderr)
        return None


def edn_lit(v) -> str:
    if isinstance(v, str):
        return '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"'
    if isinstance(v, bool):
        return "true" if v else "false"
    # edn_format hands back ImmutableList/ImmutableDict, NOT list/tuple, so an
    # isinstance check on the builtin types falls through to repr() and emits
    # Python syntax ("['a']") into what must be EDN. Test for sequence-ness.
    if hasattr(v, "__iter__") and not isinstance(v, (str, bytes)):
        return "[" + " ".join(edn_lit(x) for x in v) + "]"
    return str(v)


def main() -> int:
    commit = "--commit" in sys.argv
    ids, seen = [], set()
    for m in RECEIPT_RE.finditer(REGISTER.read_text(encoding="utf-8")):
        if m.group(1) not in seen:
            seen.add(m.group(1))
            ids.append(m.group(1))
    print(f"receipt ids in register: {len(ids)}")

    rows, no_arm, unfetchable = [], [], []
    for rid in ids:
        ev = fetch(rid)
        if ev is None:
            unfetchable.append(rid)
            continue
        body = ev.get(K("evidence/body"), {}) or {}
        out = body.get(K("outcome"), {}) or {}
        subj = ev.get(K("evidence/subject"), {}) or {}
        pid = str(subj.get(K("ref/id"), "?"))
        if out.get(K("arm-that-paid")) is None:
            no_arm.append((pid, rid))
            continue
        row = {"problem-id": pid, "receipt": rid,
               "at": str(ev.get(K("evidence/at"), "")),
               "dispatch-mode": str(body.get(K("dispatch-mode"), "")),
               "runner": str(body.get(K("runner"), ""))}
        for f in CARRY:
            v = out.get(K(f))
            if v is not None:
                row[f] = v
        rows.append(row)

    rows.sort(key=lambda r: r["at"])
    print(f"rows with arm data: {len(rows)}")
    print(f"receipts WITHOUT arm data (predate the ledger): {len(no_arm)}")
    for pid, rid in no_arm:
        print(f"    {pid:8s} {rid[:8]}")
    if unfetchable:
        print(f"UNFETCHABLE: {unfetchable}", file=sys.stderr)

    parts = [
        ";; GENERATED by scripts/build_surface_payoff.py from the run receipts.",
        ";; Do not hand-edit: the receipts are authoritative and this is a projection",
        ";; of them. Regenerate after each run's receipt is written.",
        "{:generated-from :run-receipts",
        f" :receipt-count {len(ids)}",
        f" :rows {len(rows)}",
        " ;; These receipts predate the surface-payoff fields, so they contribute no",
        " ;; row. Listed rather than dropped so the ledger's coverage is legible.",
        " :receipts-without-arm-data [" + " ".join(
            f'{{:problem "{p}" :receipt "{r}"}}' for p, r in no_arm) + "]",
        " :runs",
        " [",
    ]
    for r in rows:
        inner = " ".join(f":{k} {edn_lit(v)}" for k, v in r.items())
        parts.append("  {" + inner + "}")
    parts += [" ]}", ""]
    text = "\n".join(parts)
    loads(text)  # parse guard before writing

    if commit:
        LEDGER.write_text(text, encoding="utf-8")
        print(f"\nwrote {LEDGER}")
    else:
        print("\n(dry run - pass --commit to write)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
