#!/usr/bin/env python3
"""wiring_from_cascade.py — the plan-only wiring implied by a cascade.

  wiring_from_cascade.py CASCADE.edn OUT.edn

The cascade is the argument: which patterns, and how each narrows the space.
The wiring is the construction: what gets built, in what order, and what
witnesses it. For an instance that has not been enacted, the second is
determined by the first -- one node per pattern, building the thing that
makes its tokens true, wired by the cascade's own containment order.

So this DERIVES that wiring rather than restating it by hand, and marks it
:derived so nobody reads it as independent evidence. Each node's :form is the
cascade's own statement of the tokens it produces, and :licensed-by is the
pattern id as a keyword, not prose -- E-flight-aif W1-b.

Every interior node is hungry: nothing here has been built. An instance that
HAS been enacted gets a hand-authored wiring with satiety from its outcome
record; instance 4 is the worked example of that.
"""
import json, os, subprocess, sys


def edn(path):
    r = subprocess.run(
        ["bb", "-e",
         '(require (quote [clojure.edn :as edn]) (quote [cheshire.core :as j]))'
         f'(print (j/generate-string (edn/read-string (slurp "{path}"))))'],
        capture_output=True, text=True)
    if r.returncode:
        sys.exit(f"wiring_from_cascade: {r.stderr.strip()}")
    return json.loads(r.stdout)


def node_id(pid):
    return ":n/" + pid.split("/", 1)[1]


def main():
    src, out = sys.argv[1], sys.argv[2]
    c = edn(src)
    sha = subprocess.run(["sha256sum", src], capture_output=True, text=True).stdout.split()[0]
    pats, toks, above = c["patterns"], c["tokens"], c["above"]
    parents = {p: set() for p in pats}
    for e in above:
        parents[e["pattern"]].add(e["context"])
    children = {p: set() for p in pats}
    for e in above:
        children[e["context"]].add(e["pattern"])

    L = []
    L.append(";; WIRING DIAGRAM — M-futon-seams instance %s%s. DERIVED, plan only."
             % (c["instance"], (" candidate " + c["candidate"]) if c.get("candidate") else ""))
    L.append(";; Generated by scripts/wiring_from_cascade.py from the cascade named")
    L.append(";; below; every node's :form is that cascade's own statement of what it")
    L.append(";; produces, and :licensed-by is a typed pattern id (E-flight-aif W1-b).")
    L.append(";; Nothing here is built, so every interior node is hungry and carries")
    L.append(";; what would witness it. An enacted instance gets a hand-authored wiring")
    L.append(";; with satiety read from its outcome record -- instance 4 is that case.")
    L.append("{:mission \"M-futon-seams\"")
    L.append(" :artifact :wiring-diagram")
    L.append(" :derived true")
    L.append(" :instance %d" % c["instance"])
    if c.get("candidate"):
        L.append(" :candidate :%s" % c["candidate"])
    L.append(' :cascade {:path %s' % json.dumps(src))
    L.append('           :sha256 "%s"}' % sha)
    L.append(" :nodes")
    L.append(" [{:id :have-port :role :scope")
    L.append('   :form "the instance as the mission measures it"')
    L.append("   :satiety :full")
    L.append('   :via "boundary port: the state at this instance"}')
    L.append("")
    L.append("  {:id :want-port :role :scope")
    L.append('   :form %s' % json.dumps("; ".join(
        toks[w]["statement"] for w in sorted(c["want"]) if w in toks)))
    L.append("   :satiety {:hungry-for :payoff}")
    L.append('   :owed "not enacted: no outcome record exists for this instance"')
    L.append('   :via "boundary port: the wants this cascade is built to reach"}')
    for pid in sorted(pats):
        p = pats[pid]
        produced = sorted(p["produces"])
        form = " ".join(toks[t]["statement"] for t in produced if t in toks)
        L.append("")
        L.append("  {:id %s :role :concept" % node_id(pid))
        L.append("   :form %s" % json.dumps(form))
        L.append("   :licensed-by :%s" % pid)
        L.append("   :produces %s" % ("#{" + " ".join(":" + t for t in produced) + "}"))
        L.append("   :satiety {:hungry-for :construction}")
        L.append('   :owed "not built; witness would be the token above being true and checkable"')
        L.append("   :via %s}" % json.dumps(
            (p.get("receipt") or {}).get("reading", "")[:200]))
    L.append(" ]")
    L.append(" :hyperedges")
    L.append(" [")
    for pid in sorted(pats):
        if not parents[pid]:
            L.append("  {:kind :composes :ends [{:role :from :node :have-port} "
                     "{:role :to :node %s}]" % node_id(pid))
            L.append('   :via "a root of the cascade: it needs nothing"}')
    for e in sorted(above, key=lambda e: (e["context"], e["pattern"])):
        L.append("  {:kind :composes :ends [{:role :from :node %s} {:role :to :node %s}]"
                 % (node_id(e["context"]), node_id(e["pattern"])))
        L.append("   :kind-in-cascade :%s" % e["kind"])
        L.append("   :via %s}" % json.dumps(e["via"]))
    for pid in sorted(pats):
        if not children[pid]:
            L.append("  {:kind :composes :ends [{:role :from :node %s} "
                     "{:role :to :node :want-port}]" % node_id(pid))
            L.append('   :via "a leaf: what it produces is wanted directly"}')
    L.append(" ]}")
    open(out, "w", encoding="utf-8").write("\n".join(L) + "\n")
    print(out)


if __name__ == "__main__":
    main()
