#!/usr/bin/env python3
"""wiring_from_cascade.py — the token flow a cascade implies.

  wiring_from_cascade.py CASCADE.edn OUT.edn

The cascade is the ARGUMENT: which context sets which pattern's space. The
wiring is the CONSTRUCTION: which token one step hands to the next. They are
different relations over the same patterns, and deriving the second from the
first's edges is E-flight-aif W1-e -- it makes the picture say things the
model does not. An earlier version of this script did exactly that: it joined
every cascade LEAF to the want-port and captioned the edge "what it produces
is wanted directly", which was false for three of instance 5's four leaves.

Edges here come from tokens and nothing else. An edge exists from P to Q when
P produces a token Q needs, and it is labelled with that token. A node's ports
are its guard and its produces, so what a box takes in and hands on is
readable off the box. Three things that were invisible are now drawn:

  - a dangling output: a token produced, needed by nobody, wanted by nobody.
    Work the cascade does for no reason anyone stated.
  - an unfed want: a want token no pattern produces. The construction cannot
    reach it.
  - an inhibitor: a token one node forbids, drawn at the port where it enters,
    so a conflict is visible where it happens.
"""
import json, subprocess, sys


def edn(path):
    r = subprocess.run(
        ["bb", "-e",
         '(require (quote [clojure.edn :as edn]) (quote [cheshire.core :as j]))'
         f'(print (j/generate-string (edn/read-string (slurp "{path}"))))'],
        capture_output=True, text=True)
    if r.returncode:
        sys.exit(f"wiring_from_cascade: {r.stderr.strip()}")
    return json.loads(r.stdout)


def nid(pid):
    return pid.split("/", 1)[1] if "/" in pid else pid


def main():
    src, out = sys.argv[1], sys.argv[2]
    c = edn(src)
    sha = subprocess.run(["sha256sum", src], capture_output=True, text=True).stdout.split()[0]
    pats, toks = c["patterns"], c["tokens"]
    initial, want = set(c.get("initial") or []), set(c["want"])

    producers = {}
    for pid, p in pats.items():
        for t in p["produces"]:
            producers.setdefault(t, []).append(pid)
    consumers = {}
    for pid, p in pats.items():
        for t in p["guard"]["needs"]:
            consumers.setdefault(t, []).append(pid)

    edges, dangling, unfed = [], [], []
    for pid in sorted(pats):
        p = pats[pid]
        for t in sorted(p["guard"]["needs"]):
            if t in initial:
                edges.append((t, "have-port", nid(pid), "carries"))
            for src_pid in sorted(producers.get(t, [])):
                edges.append((t, nid(src_pid), nid(pid), "carries"))
        for t in sorted(p["guard"].get("forbids") or []):
            for src_pid in sorted(producers.get(t, [])):
                edges.append((t, nid(src_pid), nid(pid), "inhibits"))
    for w in sorted(want):
        if producers.get(w):
            for src_pid in sorted(producers[w]):
                edges.append((w, nid(src_pid), "want-port", "carries"))
        else:
            unfed.append(w)
    for t in sorted({t for p in pats.values() for t in p["produces"]}):
        if t not in want and not consumers.get(t):
            for src_pid in sorted(producers[t]):
                dangling.append((nid(src_pid), t))

    # The mission is the cascade's own :mission; the M-futon-seams cascades
    # predate that key, so they keep their name by default.
    mission = c.get("mission") or "M-futon-seams"
    L = [";; WIRING DIAGRAM — %s instance %s%s. DERIVED token flow."
         % (mission, c["instance"], (" candidate " + c["candidate"]) if c.get("candidate") else ""),
         ";; Generated by scripts/wiring_from_cascade.py from the cascade below.",
         ";; Edges are TOKENS, not the cascade's context->pattern relation: an edge",
         ";; runs from the node that produces a token to the node that needs it and",
         ";; carries that token's name. A node's ports are its guard and its",
         ";; produces. Dangling outputs and unfed wants are recorded rather than",
         ";; hidden. :licensed-by is a typed pattern id (E-flight-aif W1-b).",
         ";; Nothing here is built, so every interior node is hungry.",
         '{:mission %s' % json.dumps(mission, ensure_ascii=False),
         " :artifact :wiring-diagram",
         " :form :token-flow",
         " :derived true",
         " :instance %d" % c["instance"]]
    if c.get("candidate"):
        L.append(" :candidate :%s" % c["candidate"])
    L += [' :cascade {:path %s' % json.dumps(src),
          '           :sha256 "%s"}' % sha,
          " :nodes",
          " [{:id :have-port :role :scope",
          '   :form %s' % json.dumps(
              "the instance as the mission measures it"
              if initial else
              "the instance as the mission measures it — nothing enters here: "
              "this cascade's initial state is empty, so every token is built"),
          "   :in #{} :out %s" % ("#{" + " ".join(":" + t for t in sorted(initial)) + "}"),
          "   :satiety :full",
          '   :via "boundary port: what is true before anything is built"}',
          "",
          "  {:id :want-port :role :scope",
          '   :form %s' % json.dumps("; ".join(toks[w]["statement"] for w in sorted(want) if w in toks)),
          "   :in %s :out #{}" % ("#{" + " ".join(":" + t for t in sorted(want)) + "}"),
          "   :satiety {:hungry-for :payoff}",
          '   :owed "not enacted: no outcome record exists for this instance"',
          '   :via "boundary port: one input port per want"}']
    for pid in sorted(pats):
        p = pats[pid]
        needs = sorted(p["guard"]["needs"])
        forb = sorted(p["guard"].get("forbids") or [])
        prod = sorted(p["produces"])
        L += ["",
              "  {:id :%s :role :concept" % nid(pid),
              "   :form %s" % json.dumps(" ".join(toks[t]["statement"] for t in prod if t in toks)),
              "   :licensed-by :%s" % pid,
              "   :in %s" % ("#{" + " ".join(":" + t for t in needs) + "}"),
              "   :forbids %s" % ("#{" + " ".join(":" + t for t in forb) + "}"),
              "   :out %s" % ("#{" + " ".join(":" + t for t in prod) + "}"),
              "   :satiety {:hungry-for :construction}",
              '   :owed "not built; witness would be the output tokens being true and checkable"',
              "   :via %s}" % json.dumps((p.get("receipt") or {}).get("reading", "")[:200])]
    L += [" ]", " :edges", " ["]
    for t, a, b, kind in edges:
        L.append("  {:token :%s :from {:node :%s :port :%s} :to {:node :%s :port :%s} :kind :%s}"
                 % (t, a, t, b, t, kind))
    L += [" ]"]
    L.append(" :dangling-outputs")
    L.append(" [" + " ".join(
        '{:node :%s :token :%s :note "produced, needed by no node and wanted by nobody"}' % (n, t)
        for n, t in dangling) + "]")
    L.append(" :unfed-wants")
    L.append(" [" + " ".join(
        '{:want :%s :note "no pattern in this cascade produces it"}' % w for w in unfed) + "]}")
    open(out, "w", encoding="utf-8").write("\n".join(L) + "\n")
    print(f"{out}: {len(edges)} token edges, {len(dangling)} dangling, {len(unfed)} unfed")


if __name__ == "__main__":
    main()
