#!/usr/bin/env bb
;; Renders capability-proof-futon.edn -> a one-page markdown projection.
;; WR-8 discipline: the EDN is canonical; the rendered file is generated and
;; must not be edited in place.
;; Usage: bb render_capability_proof_futon.bb [output-path]
;; Default output: ~/code/futon3/holes/capability-proof-futon.md

(require '[clojure.edn :as edn]
         '[clojure.string :as str])

(def source-path
  (str (.getParent (io/file *file*)) "/capability-proof-futon.edn"))

(def out-path
  (or (first *command-line-args*)
      (str (System/getProperty "user.home")
           "/code/futon3/holes/capability-proof-futon.md")))

(def spec (edn/read-string (slurp source-path)))

(defn warrant-str [w]
  (if (vector? w)
    (let [[cls detail] w]
      (str (name cls)
           (when-let [n (or (:n detail) (:note detail))]
             (str " — " n))))
    (name w)))

(defn md-escape [s] (str/replace (str s) "|" "\\|"))

(def today (str (java.time.LocalDate/now)))

(def lines
  (concat
   [(str "# Capability Proof: FUTON — rendered projection")
    ""
    (str "> GENERATED " today " from `futon3c/holes/labs/M-diagramprover/capability-proof-futon.edn`.")
    "> Do not edit this file (WR-8): edit the EDN, then regenerate with"
    "> `bb futon3c/holes/labs/M-diagramprover/render_capability_proof_futon.bb`."
    ""
    (str "**TOP** — *" (get-in spec [:top :claim]) "* (" (get-in spec [:top :source]) ")")
    ""
    (get-in spec [:top :constructive-reading])
    ""
    (str "**Warrant:** " (name (get-in spec [:top :warrant]))
         " · **Discharge:** " (get-in spec [:top :discharge]))
    ""
    "## Nodes"
    ""
    "| # | Claim | Warrant | Key certificate |"
    "|---|-------|---------|-----------------|"]
   (for [n (:nodes spec)]
     (str "| " (name (:id n))
          " | " (md-escape (:claim n))
          " | " (md-escape (warrant-str (:warrant n)))
          " | " (md-escape (first (:certificates n))) " |"))
   [""
    "## Throughline lemmas (shared certificates)"
    ""]
   (for [l (:lemmas spec)]
     (str "- **" (name (:name l)) "** (" (str/join " × " (map name (:cited-from l)))
          ", " (name (:status l)) ") — " (:statement l)))
   [""
    "## Tier demands (what the stack asks of the prover ladder)"
    ""]
   (for [d (:tier-demands spec)]
     (str "- [" (name (:tier d)) ", " (name (:status d)) "] "
          (:claim d)
          " *(" (str/join ", " (map name (:nodes d))) ")*"
          (when (:note d) (str " — " (:note d)))))
   [""
    "## Invariants (WR items → nodes they govern)"
    ""
    (str/join " · "
              (for [[wr nodes] (sort-by (comp str key) (:invariants spec))]
                (str (name wr) "→" (str/join "," (map name nodes)))))
    ""
    "## Update log"
    ""]
   (for [u (:update-log spec)]
     (str "- " (:date u) " — " (:note u)))
   [""]))

(spit out-path (str/join "\n" lines))
(println "rendered ->" out-path)
